import os
import sublime

def plugin_loaded():
    # disable_native_php_package_completions
    completions_file = os.path.join(sublime.packages_path(), 'PHP', 'PHP.sublime-completions')
    if not os.path.isfile(completions_file):
        os.makedirs(os.path.dirname(completions_file))
        with open(completions_file, 'w+', encoding='utf8', newline='') as f:
            f.write('// generated by php-completions (PHP Completions Kit) to disable the native PHP package completions')
