import os

import sublime


def plugin_loaded():
    # Disable the native conflicted PHP package completions
    completions_file = os.path.join(sublime.packages_path(), 'PHP', 'PHP.sublime-completions')
    if not os.path.isfile(completions_file):
        try:
            if not os.path.isdir(os.path.dirname(completions_file)):
                os.makedirs(os.path.dirname(completions_file))
            with open(completions_file, 'w+', encoding='utf8', newline='') as f:
                f.write('// generated by PHP Completions Kit (disables the conflicted native PHP package completions)')
        except:
            pass
